# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/master/containers/ubuntu/.devcontainer/base.Dockerfile
# [Choice] Ubuntu version (use jammy or bionic on local arm64/Apple Silicon): jammy, focal, bionic
ARG VARIANT="jammy"
ARG BUN_VERSION="1.2.5"
FROM mcr.microsoft.com/vscode/devcontainers/base:0-${VARIANT}

ARG BUN_VERSION

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get install -y --no-install-recommends \
        build-essential \
        curl \
        libappindicator3-dev \
        libgtk-3-dev \
        librsvg2-dev \
        libssl-dev \
        libwebkit2gtk-4.1-dev \
        wget

USER vscode

RUN curl -fsSL https://bun.sh/install | bash -s "bun-v$BUN_VERSION"
