/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as InstallationImport } from './routes/installation'
import { Route as DoneImport } from './routes/done'
import { Route as DisksImport } from './routes/disks'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const InstallationRoute = InstallationImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => rootRoute,
} as any)

const DoneRoute = DoneImport.update({
  id: '/done',
  path: '/done',
  getParentRoute: () => rootRoute,
} as any)

const DisksRoute = DisksImport.update({
  id: '/disks',
  path: '/disks',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/disks': {
      id: '/disks'
      path: '/disks'
      fullPath: '/disks'
      preLoaderRoute: typeof DisksImport
      parentRoute: typeof rootRoute
    }
    '/done': {
      id: '/done'
      path: '/done'
      fullPath: '/done'
      preLoaderRoute: typeof DoneImport
      parentRoute: typeof rootRoute
    }
    '/installation': {
      id: '/installation'
      path: '/installation'
      fullPath: '/installation'
      preLoaderRoute: typeof InstallationImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/disks': typeof DisksRoute
  '/done': typeof DoneRoute
  '/installation': typeof InstallationRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/disks': typeof DisksRoute
  '/done': typeof DoneRoute
  '/installation': typeof InstallationRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/disks': typeof DisksRoute
  '/done': typeof DoneRoute
  '/installation': typeof InstallationRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/disks' | '/done' | '/installation'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/disks' | '/done' | '/installation'
  id: '__root__' | '/' | '/disks' | '/done' | '/installation'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DisksRoute: typeof DisksRoute
  DoneRoute: typeof DoneRoute
  InstallationRoute: typeof InstallationRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DisksRoute: DisksRoute,
  DoneRoute: DoneRoute,
  InstallationRoute: InstallationRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/disks",
        "/done",
        "/installation"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/disks": {
      "filePath": "disks.tsx"
    },
    "/done": {
      "filePath": "done.tsx"
    },
    "/installation": {
      "filePath": "installation.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
